/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jagger_Afster_Afl */

#ifndef _Included_jagger_Afster_Afl
#define _Included_jagger_Afster_Afl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jagger_Afster_Afl_afl_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_create
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jagger_Afster_Afl_afl_1create
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_new
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jagger_Afster_Afl_afl_1new
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_getName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jagger_Afster_Afl_afl_1getName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_getEntrycount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afl_afl_1getEntrycount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_rename
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afl_afl_1rename
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jagger_Afster_Afl_afl_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_save
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afl_afl_1save
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_saveNew
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afl_afl_1saveNew
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jagger_Afster_Afl
 * Method:    afl_importAfl
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afl_afl_1importAfl
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     jagger_Afster_Afl
 * Method:    jafl_getAllStrings
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jagger_Afster_Afl_jafl_1getAllStrings
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
