/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jagger_Afster_Afs */

#ifndef _Included_jagger_Afster_Afs
#define _Included_jagger_Afster_Afs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jagger_Afster_Afs_afs_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jagger_Afster_Afs_afs_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_extractEntryToFile
 * Signature: (JILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jagger_Afster_Afs_afs_1extractEntryToFile
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_extractEntryToBuffer
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jagger_Afster_Afs_afs_1extractEntryToBuffer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_extractFull
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afs_afs_1extractFull
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_replaceEntry
 * Signature: (JI[B)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afs_afs_1replaceEntry
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_replaceEntriesFromFiles
 * Signature: (J[I[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afs_afs_1replaceEntriesFromFiles
  (JNIEnv *, jobject, jlong, jintArray, jobjectArray, jint);

/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_renameEntry
 * Signature: (JILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afs_afs_1renameEntry
  (JNIEnv *, jobject, jlong, jint, jstring, jboolean);

/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_getEntryMetadata
 * Signature: (JI)Ljagger/Afster/AfsEntryMetadata;
 */
JNIEXPORT jobject JNICALL Java_jagger_Afster_Afs_afs_1getEntryMetadata
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jagger_Afster_Afs
 * Method:    afs_setEntryMetadata
 * Signature: (JILjagger/Afster/AfsEntryMetadata;Z)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afs_afs_1setEntryMetadata
  (JNIEnv *, jobject, jlong, jint, jobject, jboolean);

/*
 * Class:     jagger_Afster_Afs
 * Method:    jafs_getEntrycount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afs_jafs_1getEntrycount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jagger_Afster_Afs
 * Method:    jafs_getEntryOffset
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afs_jafs_1getEntryOffset
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     jagger_Afster_Afs
 * Method:    jafs_getEntryReservedSpace
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_jagger_Afster_Afs_jafs_1getEntryReservedSpace
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
